name: Compile proto files

on:
  workflow_dispatch:

jobs:
  Compile:
    name: Compile proto files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install grpcio-tools
          pip show grpcio-tools

      - name: Compile
        env:
          PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages:${{ env.PATH }}
        run: |
          python compile.py

      - name: tree
        run: |
          tree